version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    depends_on:
      - db

  frontend:
    build: ./frontapp
    ports:
      - 8091:80

  react:
    build: ./frontend
    command: npm run dev -- --host
    ports:
      - 5000:5173
    depends_on:
      - web  

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=cryptodb
      - POSTGRES_USER=akreem
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"
  
