# Generated by Django 3.2.23 on 2024-03-02 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapi', '0002_alter_cryptocurrency_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='price',
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('direction', models.CharField(choices=[('SHORT', 'Future Short'), ('LONG', 'Future Long'), ('SELL', 'Sell'), ('BUY', 'Buy')], default='Buy', max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('status', models.CharField(choices=[('In progress', 'In progress'), ('Canceled', 'Canceled'), ('Completed', 'Completed')], default='In progress', max_length=20)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cryptoapi.cryptocurrency')),
            ],
        ),
    ]
