# Generated by Django 3.2.23 on 2024-03-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapi', '0003_auto_20240302_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='direction',
            field=models.CharField(choices=[('SELL', 'Sell'), ('SHORT', 'Future Short'), ('LONG', 'Future Long'), ('BUY', 'Buy')], default='Buy', max_length=5),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Completed', 'Completed'), ('In progress', 'In progress')], default='In progress', max_length=20),
        ),
    ]
